services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile.dev
    ports:
      - "8080:8000"
    environment:
      DATABASE_URL: postgresql+asyncpg://postgres:postgres@db:5432/tailtrail_db
      SECRET_KEY: your-secret-key-for-development-only
      JWT_EXPIRATION: 86400
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASS: postgres
      DB_NAME: tailtrail_db
      ECHO_SQL: "true"
      DEBUG_LOGS: "true"
    volumes:
      - .:/app
      - /app/.venv  # Exclude the .venv directory from host mount
    command: ["uv", "run", "uvicorn", "src.app:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    depends_on:
      - db

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: tailtrail_db
    ports:
      - "5557:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres"]

volumes:
  postgres_data:
