"""create post

Revision ID: 4f7223597601
Revises: eaf2d61a2e32
Create Date: 2025-07-08 16:34:22.362728

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4f7223597601'
down_revision: Union[str, None] = 'eaf2d61a2e32'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('posts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('pet_name', sa.String(length=100), nullable=False),
    sa.Column('pet_species', sa.String(length=50), nullable=False),
    sa.Column('pet_breed', sa.String(length=100), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('gender', sa.String(length=10), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('color', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('location_name', sa.String(length=200), nullable=False),
    sa.Column('contact_phone', sa.String(length=20), nullable=False),
    sa.Column('last_seen_latitude', sa.Float(), nullable=False),
    sa.Column('last_seen_longitude', sa.Float(), nullable=False),
    sa.Column('images', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('posts')
    # ### end Alembic commands ###
