"""create_user_blocks_table

Revision ID: 5797cf860245
Revises: 69e10d3ecf76
Create Date: 2025-07-13 13:11:08.845102

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import UUID


# revision identifiers, used by Alembic.
revision: str = '5797cf860245'
down_revision: Union[str, None] = '69e10d3ecf76'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'user_blocks',
        sa.Column('id', UUID(as_uuid=True), nullable=False),
        sa.Column('blocker_id', UUID(as_uuid=True), nullable=False),
        sa.Column('blocked_id', UUID(as_uuid=True), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['blocked_id'], ['users.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['blocker_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('blocker_id', 'blocked_id', name='unique_user_block')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_blocks')
    # ### end Alembic commands ###
