"""add blocks table

Revision ID: 7fe74aee49e3
Revises: d49ce72b2223
Create Date: 2025-07-13 14:26:06.042090

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7fe74aee49e3'
down_revision: Union[str, None] = 'd49ce72b2223'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blocks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('blocker_id', sa.UUID(), nullable=False),
    sa.Column('blocked_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['blocked_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['blocker_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('blocker_id', 'blocked_id', name='unique_block_pair')
    )
    op.drop_table('user_blocks')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_blocks',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('blocker_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('blocked_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['blocked_id'], ['users.id'], name='user_blocks_blocked_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['blocker_id'], ['users.id'], name='user_blocks_blocker_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='user_blocks_pkey'),
    sa.UniqueConstraint('blocker_id', 'blocked_id', name='unique_user_block')
    )
    op.drop_table('blocks')
    # ### end Alembic commands ###
