"""add phone and image_url to users table

Revision ID: a95808c7c5bb
Revises: 069e7cc66d82
Create Date: 2025-07-03 19:32:52.696656

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a95808c7c5bb'
down_revision: Union[str, None] = '069e7cc66d82'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
