"""edit post

Revision ID: d49ce72b2223
Revises: 32c533488618
Create Date: 2025-07-10 06:59:56.411074

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd49ce72b2223'
down_revision: Union[str, None] = '32c533488618'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('posts', 'pet_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('posts', 'pet_species',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('posts', 'pet_breed',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('posts', 'age',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('posts', 'gender',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
    op.alter_column('posts', 'weight',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('posts', 'color',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('posts', 'description',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('posts', 'location_name',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    op.alter_column('posts', 'contact_phone',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('posts', 'last_seen_latitude',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('posts', 'last_seen_longitude',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('posts', 'images',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               nullable=True)
    op.alter_column('posts', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('posts', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('posts', 'images',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               nullable=False)
    op.alter_column('posts', 'last_seen_longitude',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('posts', 'last_seen_latitude',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('posts', 'contact_phone',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('posts', 'location_name',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    op.alter_column('posts', 'description',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('posts', 'color',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('posts', 'weight',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('posts', 'gender',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
    op.alter_column('posts', 'age',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('posts', 'pet_breed',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('posts', 'pet_species',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('posts', 'pet_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    # ### end Alembic commands ###
